version: "3.7"

services:
  app:
    user: $UID:$GID
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    user: $UID:$GID
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend:Z
    command: >
      sh -c "npm run serve"