version: "3.7"

services:
  app:
    container_name: quering-app
    user: $UID:$GID
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    command: >
      sh -c "pip install -r requirements.txt && tail -f /dev/null"
    environment:
      - DB_HOST=db
      - DB_NAME=asiamarket
      - DB_USER=adminmarket
      - DB_PASS=postgres15
      - SECRET_KEY=3bh=u&qqo2mn&n0*8h$$@kw&k(j#$$al&jc@wr$$^%qxb_=^hgqq-
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.sendgrid.net
      - EMAIL_HOST_USER=thaimarketexpress
      - EMAIL_HOST_PASSWORD=thaimarketexpress55
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - DEBUG=True
    depends_on:
      - db

  db:
    container_name: quering-db
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=asiamarket
      - POSTGRES_USER=adminmarket
      - POSTGRES_PASSWORD=postgres15
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./docker_volumes/pg_data:/var/lib/postgresql/data

  frontend:
    container_name: quering-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend:Z
    command: >
      sh -c "tail -f /dev/null"

  nginx:
    container_name: quering-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    depends_on:
      - frontend
      - app

volumes:
  media_volume:
  static_volume:
