version: "3.7"

services:
  app:
    user: $UID:$GID
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "pip install -r requirements.txt && tail -f /dev/null"
    environment:
      - DB_HOST=db
      - DB_NAME=asiamarket
      - DB_USER=adminmarket
      - DB_PASS=postgres15
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=asiamarket
      - POSTGRES_USER=adminmarket
      - POSTGRES_PASSWORD=postgres15
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./docker_volumes/pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend:Z
    command: >
      sh -c "tail -f /dev/null"
