version: "3.7"

services:
  app:
    container_name: quering-app
    user: $UID:$GID
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "pip install -r requirements.txt && yes | python manage.py collectstatic && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=asiamarket
      - DB_USER=adminmarket
      - DB_PASS=postgres15
    depends_on:
      - db

  db:
    container_name: quering-db
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=asiamarket
      - POSTGRES_USER=adminmarket
      - POSTGRES_PASSWORD=postgres15
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./docker_volumes/pg_data:/var/lib/postgresql/data

  frontend:
    container_name: quering-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: >
      sh -c "tail -f /dev/null"

  nginx-ssl:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'demo.benning.website'
      SITES: 'demo.benning.website=nginx:80'

  nginx:
    container_name: quering-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - app

volumes:
  ssl_data:
