# Generated by Django 2.2.10 on 2020-02-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('BankTransfer', 'BankTransfer')], default='PayPal', max_length=50),
            preserve_default=False,
        ),
    ]
