# Generated by Django 2.2.9 on 2020-02-05 13:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200205_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(null=True, upload_to=core.models.product_image_path),
        ),
    ]
