# Generated by Django 2.2.11 on 2020-03-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
