# Generated by Django 2.2.10 on 2020-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Waiting', 'Waiting for delivery'), ('Shipping', 'In the process of shipping'), ('Delivered', 'Delivered')], default='Waiting', max_length=50),
        ),
    ]
