# Generated by Django 2.2.10 on 2020-02-20 11:03

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200218_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=core.models.bill_payment_image)),
                ('time_transfer', models.DateTimeField()),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
    ]
