# Generated by Django 2.2.10 on 2020-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymentbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbill',
            name='approve_status',
            field=models.BooleanField(default=False),
        ),
    ]
