# Generated by Django 2.2.10 on 2020-02-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentbill_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('PayPal', 'PayPal'), ('BankTransfer', 'BankTransfer')], max_length=50, null=True),
        ),
    ]
