# Generated by Django 2.2.10 on 2020-02-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200213_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Code'),
        ),
    ]
