# Generated by Django 2.2.10 on 2020-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=255, max_digits=7),
            preserve_default=False,
        ),
    ]
