# Generated by Django 2.2.10 on 2020-02-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200213_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', unique=True),
        ),
    ]
