# Generated by Django 2.2.10 on 2020-02-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200213_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
